### ISSUE TITLE
不支持自定义启动端口

### ISSUE THREAD

**Issue by EchoNoReturn** [goldpankit/goldpankit#1]
在此，首先感谢作者的贡献。
我遇到了这样的问题：我已经运行了nginx在本机，80端口被其他程序占用的情况下我会需要切换端口。当我使用kit -h 或者kit --help 发现没有正常获取到帮助信息，我立刻对源码进行查看，发现端口是写死的。如果可以，我推荐可以把端口写活，并且从执行命令上给出对应的友好提示。

![image](https://github.com/goldpankit/goldpankit/assets/95645011/46d226c9-2962-4e0a-94b4-799cf2a9edcd)

port 可以尝试这样获得：
```javascript
process.argv.forEach((val, index) => {  
  console.log(`${index}: ${val}`);  
});  
```

**Comment by caesar-liu** [comment]
非常抱歉，现在才看到你的问题！
目前已经支持，可使用`kit -p`或`kit --port`指定端口号。默认端口号已调整为`8130`。
